title: Customise your Raspberry Pi Desktop
hero_image: images/banner.png
description: Change the background image, colour scheme and settings for your Raspberry Pi Desktop to make it look and work the way you want.
version: 4
listed: false
copyedit: false
last_tested: "2019-04-25"
steps:
  - title: Introduction
  - title: Customise the wallpaper
  - title: Choose your favourite wallpaper
  - title: Customise the taskbar
  - title: Choose your favourite taskbar and system settings
  - title: What next?
