title: custom-pi-desktop
hero_image: images/banner.png
description: custom-pi-desktop description
version: 4
listed: false
copyedit: false
last_tested: "2019-04-25"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
