title: custom-pi-desktop
hero_image: images/banner.png
description: custom-pi-desktop description
version: 4
listed: false
copyedit: false
last_tested: "2019-04-25"
steps:
  - title: Introduction
  - title: Customise the wallpaper
  - title: Choose your favourite wallpaper
  - title: Customise the taskbar
  - title: Choose your favourite taskbar and system settings
  - title: What next?
